name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: docker/build-push-action@v1
      with:
        push: false
     -
      name: Set up CoPilot JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
     -
      name: Upload to CoPilot
      if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)